mod hashmaps;
pub use hashmaps::pin_map;
pub use hashmaps::reuse_pinned_map;
pub use hashmaps::rm_pinned_map;
pub use hashmaps::GStats;
pub use hashmaps::SharedMaps;
pub use hashmaps::CGROUP_MAP_PATH;
pub use hashmaps::CMAP;
pub use hashmaps::GMAP;
pub use hashmaps::SCHED_GROUP_MAP_PATH;

mod hashmaps_safe;
pub use hashmaps_safe::SharedMapsSafe;

mod bpf_skel;
pub use bpf_skel::bpf_fsched;

/// Autogenerated @ target/debug/build/iluvatar_finesched-.*/out/bpf_intf.rs
///
/// #[repr(C)]
/// #[derive(Debug, Copy, Clone)]
/// pub struct SchedGroupStatus {
///     pub cur_cgroup_prefix: [::std::os::raw::c_char; 100usize],
/// }
///
/// #[repr(C)]
/// #[derive(Debug, Copy, Clone)]
/// pub struct SchedGroupChrs {
///     pub corebitmask: cpumask,
///     pub timeslice: u64_,
///     pub dsqid: u64_,
///     pub perf: u32_,
///     pub status: SchedGroupStatus_t,
/// }
pub mod bpf_intf;
pub use bpf_intf::consts_RESERVED_GID_SWITCH_BACK;
pub use bpf_intf::CgroupChrs;
pub use bpf_intf::SchedGroupChrs;
pub use bpf_intf::SchedGroupID;
pub use bpf_intf::SchedGroupStats;

mod sched;
pub use sched::load_bpf_scheduler_async;

mod groups;
pub use groups::PreAllocatedGroups;
pub use groups::PreallocGroupsConfig;
pub use groups::SchedGroup;

mod utils;
pub use utils::default_cpumask;
